version: "3"

services:
  #### 1. Traefil reverse proxy and load balancer
  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    command:
      # Traefik static config
      # logs
      - --log=true
      - --log.filePath=/logs/traefik.log
      - --log.level=DEBUG # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - --accessLog=true
      - --accessLog.filePath=/logs/access.log
      - --accessLog.bufferingSize=100 # Configuring a buffer of 100 lines
      - --accessLog.filters.statusCodes=204-299,400-499,500-599

      # LetsEncrypt Staging Server - uncomment when testing
      - --certificatesResolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory

      # Make sure your firewall allows HTTP/HTTPS
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443

      - --api=true
      - --providers.docker=true
 
      # LetsEncrypt Staging Server - uncomment when testing
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http
      - --certificatesresolvers.letsencrypt.acme.email=${ADMIN_EMAIL} # Your email for Let's Encrypt notifications
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    labels:
      # Redirect all HTTP traffic to HTTPS
      - traefik.http.routers.to-https.rule=HostRegexp(`{host:.+}`)
      - traefik.http.routers.to-https.entrypoints=http
      - traefik.http.routers.to-https.middlewares=to-https

      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.middlewares=auth
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=${CERT_RESOLVER}

      - traefik.http.middlewares.to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_PASSWORD_HASH}
      
    ports:
        # HTTP port
      - 80:80
      - 443:443

    volumes:
      - ./docker/cert/letsencrypt:/letsencrypt # Store's Let's Encrypt certificates here; make sure it's secure
      - ./docker/logs/traefik:/logs
      - /var/run/docker.sock:/var/run/docker.sock:ro

  #### 2. vLLM server 
  vllm:
    image: vllm/vllm-openai:latest
    restart: unless-stopped
    # vLLM server config
    command:
      --model ${MODEL_NAME}
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface:rw
    # Allocate NVIDIA GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['0']
    labels:
      - "traefik.http.routers.vllm.tls=true"
      - "traefik.http.routers.vllm.entrypoints=https"
      - "traefik.http.routers.vllm.rule=Host(`${DOMAIN}`)" # Replace with your domain
      - "traefik.http.services.vllm.loadbalancer.server.port: 8000" # Port of vLLM server
      - "traefik.http.routers.https.tls.certresolver=${CERT_RESOLVER}" # lets encrypt for public server